### ISSUE TITLE
Front End UI

### ISSUE THREAD

**Issue by randomslap** [randomslap/Project1#1]
## User Story
The user will have a clean UI to navigate through the website.
## To-Do
- [ ] initialize index.html
- [ ] navbar with search function in header tag
- [ ] body tag contains Google cards that displays different content
